Dev check unique and lock/unlock step flow
cloudoptim/qptestflowcore pull request #4
Opened 2021-04-16 04:46 UTC by chienpm-dotnet

1. Api is to check for step name uniqueness 
2. API to check Testcase name uniqueness
3. Api to lock/unlock testcase
4. Api to check test case is locked by other user

2021-04-16 11:54 UTC, QParavin requested changes

2021-04-16 11:54 UTC, QParavin commented on QPCore/Service/TestFlowService.cs
> +                item.Islocked = true;
can you add last updated user, so that we can identify who locked it

2021-04-16 11:54 UTC, QParavin commented on QPCore/Service/TestFlowService.cs
> +                .Any(p => p.TestFlowId == id && p.Islocked == true);
Locked should be validated against user.

2021-04-19 16:34 UTC, chienpm-dotnet commented on QPCore/Service/TestFlowService.cs
> +                item.Islocked = true;
I have applied your request.

2021-04-19 16:34 UTC, chienpm-dotnet commented on QPCore/Service/TestFlowService.cs
> +                .Any(p => p.TestFlowId == id && p.Islocked == true);
I have applied your request.

2021-04-19 16:44 UTC, merged